Code from Monday 27.05.
jovansimonovic/isa.fe pull request #4
Opened 2024-05-29 12:21 UTC by jovansimonovic

Frontend code from monday's lectures. Please confirm PR

2024-05-30 00:56 UTC, pbisevac requested changes
Continue with this branch and add code from 29.05. 

We have alot of bugs in this branch, you can fix it with code from 10. labs.

2024-05-30 07:52 UTC, jovansimonovic reviewed
Understood. Will request re-review once I'm done

2024-06-02 23:06 UTC, pbisevac requested changes
Continue with this branch. We have to fix some bugs.

2024-06-02 23:17 UTC, jovansimonovic reviewed
Code from may 27th, 29th and 31st. Got a bit tangled up in some merge conflicts x), finally resolved them (at least I think I did :P). Praying to God the code still works :D

2024-06-02 23:29 UTC, pbisevac commented
> Code from may 27th, 29th and 31st. Got a bit tangled up in some merge conflicts x), finally resolved them (at least I think I did :P). Praying to God the code still works :D

hehe, perfect practice 🥇

2024-06-02 23:49 UTC, jovansimonovic reviewed
App works now. Cleaned up the files left from all the chaos from conflicts. Is it safe to merge now?

2024-06-03 21:10 UTC, pbisevacSing approved these changes
You can merge but dont forget to read comments.

2024-06-03 21:10 UTC, pbisevacSing commented on src/hooks/useRefreshToken.js
> +      await update({
We have a bug here. This must be changed. We can not update the session here.

2024-06-03 21:10 UTC, pbisevacSing commented on src/hooks/useAuth.js
> +          const refreshTokenResponse = await refreshToken();
Here too, this is a bug. you must fix it. Try with another branch.

2024-06-03 21:22 UTC, pbisevacSing approved these changes

2024-06-03 21:22 UTC, pbisevacSing commented on src/hooks/useRefreshToken.js
> +  const { data: session } = useSession();
missing update method here

2024-06-03 21:33 UTC, merged